services:
  app:
    build: .
    container_name: laravel_app
    ports:
      - "8111:80"
    volumes:
      - db:/var/www/database
      - storage:/var/www/storage
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_URL=http://localhost:8111

      - REVERB_HOST=localhost
      - REVERB_PORT=8111

      # Cấu hình Database (Dùng SQLite)
      - DB_CONNECTION=sqlite
      - SESSION_DRIVER=file

    restart: unless-stopped

volumes:
  db:
  storage: