services:
  app:
    image: ghcr.io/524h0003/project503073:main
    container_name: laravel_app
    ports:
      - "8000:80"
    volumes:
      - ./database:/var/www/html/database
      - ./storage:/var/www/html/storage
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_URL=http://localhost:8000

      # Cấu hình Database (Dùng SQLite)
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite

      # CẤU HÌNH SMTP EMAIL (Thay đổi các giá trị dưới đây)
      - MAIL_MAILER=smtp
      - MAIL_HOST=smtp.gmail.com
      - MAIL_PORT=587
      - MAIL_USERNAME=vietuk.nguyen@gmail.com
      - MAIL_PASSWORD=tcod hvvf lmjb cuvl
      - MAIL_ENCRYPTION=tls
      - MAIL_FROM_ADDRESS="${MAIL_USERNAME}"
      - MAIL_FROM_NAME="${APP_NAME}"

    restart: unless-stopped
    command: >
      sh -c "php artisan migrate --force && 
             php artisan storage:link"