name: Test package

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    runs-on: ubuntu-latest
    
    steps:          
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # --- PHẦN 1: THIẾT LẬP PHP & COMPOSER ---
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3' # Thay đổi version phù hợp với dự án của bạn
          extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, bcmath, dom, curl
          coverage: none

      - name: Install Composer Dependencies
        run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      # --- PHẦN 2: THIẾT LẬP NODE (Cho Vite/Mix) ---
      - uses: actions/setup-node@v4
        with:
          node-version: latest

      - uses: pnpm/action-setup@v3
        with:
          version: 10.9.0
          run_install: false
          cache: true

      - name: Update dependencies
        run: pnpm update

      - name: Format code
        run: pnpm format

      - name: Build Assets (Vite)
        run: pnpm build
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
